# This is a basic workflow to help you get started with Actions

name: Build books.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SIZE: a6 # 対応はa4, a5, a6, b5, shinsho
  MUKI: tate # tateが縦組み、yokoが横組み（※ yokoは要修正）

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # reviewdog-github-check:
  #   name: reviewdog (github-check)
  #   runs-on: ubuntu-latest

  #   steps:
  #       #reviewdogのアクション
  #     - uses: reviewdog/action-setup@v1
  #       with:
  #         reviewdog_version: latest

  #       #textlintを動かすためのnodeアクション
  #     - uses: actions/setup-node@v3

  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: recursive

  #     - name: cache-node-modules
  #       #stepsが失敗(文章の乱れ)した場合でもcacheを取得するようにする
  #       uses: pat-s/always-upload-cache@v2.1.3
  #       env:
  #         cache-name: cache-node-modules
  #       with:
  #         path: ~/.npm
  #         key: node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           node-

  #     - name: Install textlint
  #       run:  'npm install --save-dev textlint textlint-rule-preset-smarthr textlint-rule-prh textlint-plugin-review'
      
  #     - name: Install dependent module
  #       run: npm install

  #     - name: Execute textlint
  #       env:
  #         REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         npx textlint -f checkstyle chapter/*.re wiki/*.md README.md \
  #         | reviewdog -f=checkstyle -name="textlint" -diff="git diff ${{ github.event.pull_request.base.ref }}" -reporter=github-pr-review -level="error"

  epub:
    # needs: reviewdog-github-check
    name: EPUB
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/huideyeren/vivliostyle-review-docker:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: 現在時刻を取得
        env: 
          TZ: "Asia/Tokyo" # タイムゾーンを指定
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H%M')"
             # '%Y-%m-%d %H:%M'の部分を書き換えれば、任意の表示に変更できる。
      - name: 現在時刻を確認
        run: echo ${{ steps.date.outputs.date }} # 2022-01-03 10:42
      - name: Node.jsのパッケージをインストール
        run: pnpm install
      - name: SCSSのコンパイル
        run: pnpm run style:${{ env.SIZE }}-${{ env.MUKI }}-no-bleed
      - name: Rubyのパッケージをインストール
        run: bundle install
      - name: EPUBの生成
        run: bundle exec rake epub
      - name: 成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('inokashira-template_{0}_{1}', 'epub', steps.date.outputs.date) }}
          path: book.epub

  print-pdf:
    # needs: reviewdog-github-check
    name: 塗り足しのある印刷用PDF
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/huideyeren/vivliostyle-review-docker:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: 現在時刻を取得
        env: 
          TZ: "Asia/Tokyo" # タイムゾーンを指定
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H%M')"
              # '%Y-%m-%d %H:%M'の部分を書き換えれば、任意の表示に変更できる。
      - name: 現在時刻を確認
        run: echo ${{ steps.date.outputs.date }} # 2022-01-03 10:42
      - name: Node.jsのパッケージをインストール
        run: pnpm install
      - name: SCSSのコンパイル
        run: pnpm run style:${{ env.SIZE }}-${{ env.MUKI }}
      - name: Rubyのパッケージをインストール
        run: bundle install
      - name: Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 画像の白黒化
        run: | 
          python -m pip install --upgrade pip 
          python -m pip install anshitsu
          pwd | python grayscaling.py >> .grayscaling.log
      - name: 画像白黒化のログ確認
        run: cat .grayscaling.log
      - name: PDFの生成
        run: REVIEW_CONFIG_FILE=config-print.yml REVIEW_VSCLI_USESANDBOX=true REVIEW_VSCLI_GRAYSCALE=true bundle exec rake vivliostyle
      - name: 成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('inokashira-template_{0}_{1}', 'print-pdf', steps.date.outputs.date) }}
          path: book.pdf

  print-pdf-no-bleed:
    # needs: reviewdog-github-check
    name: 塗り足しのない印刷用PDF
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/huideyeren/vivliostyle-review-docker:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: 現在時刻を取得
        env: 
          TZ: "Asia/Tokyo" # タイムゾーンを指定
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H%M')"
              # '%Y-%m-%d %H:%M'の部分を書き換えれば、任意の表示に変更できる。
      - name: 現在時刻を確認
        run: echo ${{ steps.date.outputs.date }} # 2022-01-03 10:42
      - name: Node.jsのパッケージをインストール
        run: pnpm install
      - name: SCSSのコンパイル
        run: pnpm run style:${{ env.SIZE }}-${{ env.MUKI }}-no-bleed
      - name: Rubyのパッケージをインストール
        run: bundle install
      - name: Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 画像の白黒化
        run: | 
          python -m pip install --upgrade pip 
          python -m pip install anshitsu
          pwd | python grayscaling.py >> .grayscaling.log
      - name: 画像白黒化のログ確認
        run: cat .grayscaling.log
      - name: PDFの生成
        run: REVIEW_CONFIG_FILE=config-print.yml EVIEW_VSCLI_USESANDBOX=true REVIEW_VSCLI_GRAYSCALE=true bundle exec rake vivliostyle
      - name: 成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('inokashira-template_{0}_{1}', 'print-pdf-no-bleed', steps.date.outputs.date) }}
          path: book.pdf

  ebook-pdf:
    # needs: reviewdog-github-check
    name: 電子書籍用PDF
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/huideyeren/vivliostyle-review-docker:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: 現在時刻を取得
        env: 
          TZ: "Asia/Tokyo" # タイムゾーンを指定
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H%M')"
              # '%Y-%m-%d %H:%M'の部分を書き換えれば、任意の表示に変更できる。
      - name: 現在時刻を確認
        run: echo ${{ steps.date.outputs.date }} # 2022-01-03 10:42
      - name: Node.jsのパッケージをインストール
        run: pnpm install
      - name: SCSSのコンパイル
        run: pnpm run style:${{ env.SIZE }}-${{ env.MUKI }}-no-bleed
      - name: Rubyのパッケージをインストール
        run: bundle install
      - name: PDFの生成
        run: REVIEW_VSCLI_USESANDBOX=true bundle exec rake vivliostyle
      - name: 成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('inokashira-template_{0}_{1}', 'ebook-pdf', steps.date.outputs.date) }}
          path: book.pdf